services:
  - type: web
    name: backend-flask
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    workingDir: backend
    envVars:
      - key: NEON_DATABASE_URL 
        sync: false