services:
  - type: web
    name: backend-flask
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: NEON_DATABASE_URL
        sync: false  